services:
    frontend:
        build: ./frontend
        ports:
            -   5173:5173
        depends_on:
            -   backend
    backend:
        build: ./backend

        ports:
            -   8000:80
        depends_on:
            -   db
        env_file:
            - ./backend/.env
    db:
        image: mysql
        ports:
            -   3306:3306
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: true
            MYSQL_DATABASE: el_projekte_grande

